apiVersion: v1
kind: Namespace
metadata:
  name: ocpdoom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    app: ocpdoom
    app.kubernetes.io/component: ocpdoom
    app.kubernetes.io/instance: ocpdoom
  name: ocpdoom
  namespace: ocpdoom
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: ocpdoom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: ocpdoom
    spec:
      containers:
      - image: quay.io/ocpdoom/ocpdoom:amd64
        imagePullPolicy: IfNotPresent
        name: ocpdoom
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-ocpdoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: ocpdoom
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocpdoom
    app.kubernetes.io/component: ocpdoom
    app.kubernetes.io/instance: ocpdoom
  name: ocpdoom
  namespace: ocpdoom
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32077
    port: 5900
    protocol: TCP
    targetPort: 5900
  selector:
    deployment: ocpdoom
  sessionAffinity: None
  type: NodePort
